apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-todo
  labels:
    app: todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
      - name: todo
        image: xphyr/example_golang_todo:v1
        command: [/app/main]
        args: [ "-user", "SA", "-password", "<pass goes here>", "-server", "<service IP goes here>", "-database", "database name goes here>"]
        ports:
        - containerPort: 3000
